import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import Provider from "@repo/ui/components/providers";
import AdminWrapper from "@/components/adminWrapper";
import { GreenChatWidget } from "@/components/ai/green-chat-widget";
import Aiwrapper from "@/components/ai/ai-wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><SessionProviderWrapper>
          <Provider>
            <AdminWrapper>{children}</AdminWrapper>
          </Provider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
