"use client";

import React, { useState } from "react";
import { CheckCircle, FileDown, Loader2 } from "lucide-react";
import { PdfConfig } from "@/type/ai-conversation/report";

interface PdfDownloadCardProps {
  config: PdfConfig;
}

declare global {
  interface Window {
    jspdf?: {
      jsPDF: new (options?: { orientation?: "portrait" | "landscape"; unit?: string; format?: string }) => any;
    };
  }
}

const generatePdf = (config: PdfConfig) => {
  if (!window.jspdf?.jsPDF) {
    throw new Error("PDF library is not loaded yet.");
  }

  const doc = new window.jspdf.jsPDF({
    orientation: config.orientation || "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("CLMS", margin, 16);

  doc.setFontSize(12);
  doc.text(config.title, margin, 24);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin, 16, { align: "right" });
  if (config.period) {
    doc.text(`Period: ${config.period}`, pageWidth - margin, 21, { align: "right" });
  }

  let startY = 30;
  if (config.description) {
    const split = doc.splitTextToSize(config.description, pageWidth - margin * 2);
    doc.text(split, margin, startY);
    startY += split.length * 4 + 4;
  }

  if (config.summary && Object.keys(config.summary).length > 0) {
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, startY, pageWidth - margin * 2, 16, 1.5, 1.5, "FD");
    let x = margin + 3;
    doc.setFontSize(8);
    Object.entries(config.summary).slice(0, 4).forEach(([k, v]) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, x, startY + 6);
      doc.setFont("helvetica", "normal");
      doc.text(String(v), x, startY + 12);
      x += 46;
    });
    startY += 22;
  }

  doc.autoTable({
    startY,
    head: [config.headers],
    body: config.rows,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 2.5, textColor: [51, 65, 85] },
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: "bold", fontSize: 8.5 },
    didParseCell: (data: any) => {
      const text = String(data.cell.raw || "").toUpperCase();
      if (["MISMATCH", "FAILED", "NOT_FOUND_IN_DB", "NOT_FOUND_IN_CHALLAN", "NON-COMPLIANT"].includes(text)) {
        data.cell.styles.textColor = [220, 38, 38];
        data.cell.styles.fontStyle = "bold";
      }
      if (["MATCH", "VERIFIED", "COMPLIANT", "ACTIVE"].includes(text)) {
        data.cell.styles.textColor = [22, 163, 74];
        data.cell.styles.fontStyle = "bold";
      }
      if (data.section === "body" && /^[₹$€£]?\s*[\d,.]+%?$/.test(String(data.cell.raw || ""))) {
        data.cell.styles.halign = "right";
      }
    },
  });

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by CLMS AI", margin, pageHeight - 8);
    doc.text(`Page ${i} of ${pages}`, pageWidth - margin, pageHeight - 8, { align: "right" });
  }

  doc.save(`${config.filename}.pdf`);
};

function PdfDownloadCard({ config }: PdfDownloadCardProps) {
  const [downloading, setDownloading] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      generatePdf(config);
      setDone(true);
    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("Unable to generate PDF right now. Please try again in a moment.");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="my-2 w-full max-w-sm overflow-hidden rounded-lg border border-blue-200 bg-white">
      <div className="flex items-center gap-2 border-b border-blue-100 bg-blue-50 px-3 py-2">
        <FileDown className="h-4 w-4 text-blue-700" />
        <div>
          <p className="text-sm font-semibold text-blue-900">PDF Report Ready</p>
          <p className="text-[11px] text-blue-700">{config.filename}.pdf</p>
        </div>
      </div>
      <div className="space-y-2 p-3">
        <div>
          <p className="text-[11px] uppercase tracking-wide text-slate-500">Title</p>
          <p className="text-sm text-slate-800">{config.title}</p>
        </div>
        {config.period ? (
          <div>
            <p className="text-[11px] uppercase tracking-wide text-slate-500">Period</p>
            <p className="text-sm text-slate-800">{config.period}</p>
          </div>
        ) : null}
        <button
          onClick={handleDownload}
          disabled={downloading}
          className={`inline-flex w-full items-center justify-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors ${
            done ? "border border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100" : "bg-blue-700 text-white hover:bg-blue-800"
          } disabled:cursor-not-allowed disabled:opacity-70`}
        >
          {downloading ? <Loader2 className="h-4 w-4 animate-spin" /> : done ? <CheckCircle className="h-4 w-4" /> : <FileDown className="h-4 w-4" />}
          {downloading ? "Generating..." : done ? "Download Again" : "Download Report"}
        </button>
      </div>
    </div>
  );
}

export default PdfDownloadCard;
